<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250418115340 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE administrative_identifier (id INT AUTO_INCREMENT NOT NULL, siret BIGINT DEFAULT NULL, ape VARCHAR(15) DEFAULT NULL, UNIQUE INDEX UNIQ_A446D52326E94372 (siret), UNIQUE INDEX UNIQ_A446D523A4B39424 (ape), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE association (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, sigle VARCHAR(255) NOT NULL, description VARCHAR(2048) DEFAULT NULL, fede_filliere VARCHAR(255) DEFAULT NULL, fede_territoire VARCHAR(255) DEFAULT NULL, local VARCHAR(255) DEFAULT NULL, adresse_mail VARCHAR(255) DEFAULT NULL, date_election DATE DEFAULT NULL, UNIQUE INDEX UNIQ_FD8521CC77153098 (code), UNIQUE INDEX UNIQ_FD8521CC5E237E06 (name), UNIQUE INDEX UNIQ_FD8521CC8776B952 (sigle), UNIQUE INDEX UNIQ_FD8521CCA1207B9E (adresse_mail), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE association_profil (association_id INT NOT NULL, profil_id INT NOT NULL, INDEX IDX_D5A287E0EFB9C8A5 (association_id), INDEX IDX_D5A287E0275ED078 (profil_id), PRIMARY KEY(association_id, profil_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE badge (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, categorie VARCHAR(255) DEFAULT NULL, description VARCHAR(2048) DEFAULT NULL, date_creation DATE DEFAULT NULL, UNIQUE INDEX UNIQ_FEF0481D77153098 (code), UNIQUE INDEX UNIQ_FEF0481D5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE badge_profil (badge_id INT NOT NULL, profil_id INT NOT NULL, INDEX IDX_D46A11D2F7A2C2FC (badge_id), INDEX IDX_D46A11D2275ED078 (profil_id), PRIMARY KEY(badge_id, profil_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bank_account (id INT AUTO_INCREMENT NOT NULL, chart_of_accounts_id INT DEFAULT NULL, location_id INT DEFAULT NULL, account_number INT DEFAULT NULL, rib_bank_code INT DEFAULT NULL, rib_branch_code INT DEFAULT NULL, rib_account_number BIGINT DEFAULT NULL, rib_key INT DEFAULT NULL, iban VARCHAR(64) DEFAULT NULL, bic VARCHAR(64) DEFAULT NULL, last_count_date DATE NOT NULL, UNIQUE INDEX UNIQ_53A23E0AB1A4D127 (account_number), UNIQUE INDEX UNIQ_53A23E0ABD1BC4FE (rib_account_number), UNIQUE INDEX UNIQ_53A23E0AFAD56E62 (iban), INDEX IDX_53A23E0A196B9FF2 (chart_of_accounts_id), INDEX IDX_53A23E0A64D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bank_detail (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, iban VARCHAR(64) DEFAULT NULL, bic VARCHAR(64) DEFAULT NULL, INDEX IDX_E6350EE9395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp (id INT AUTO_INCREMENT NOT NULL, exercice_id INT NOT NULL, categorie VARCHAR(255) DEFAULT NULL, designation VARCHAR(1024) DEFAULT NULL, expected_amount DOUBLE PRECISION DEFAULT NULL, reallocate_amount DOUBLE PRECISION DEFAULT NULL, INDEX IDX_46176AE689D40298 (exercice_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE catalog_discount (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(15) DEFAULT NULL, name VARCHAR(50) DEFAULT NULL, description VARCHAR(1024) DEFAULT NULL, UNIQUE INDEX UNIQ_D3376A1077153098 (code), UNIQUE INDEX UNIQ_D3376A105E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE catalog_service (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, amount_ht DOUBLE PRECISION DEFAULT NULL, tva_rate DOUBLE PRECISION DEFAULT NULL, amount_ttc DOUBLE PRECISION DEFAULT NULL, description VARCHAR(1024) DEFAULT NULL, UNIQUE INDEX UNIQ_EE2F67FE77153098 (code), UNIQUE INDEX UNIQ_EE2F67FE5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE chart_of_accounts (id INT AUTO_INCREMENT NOT NULL, code INT DEFAULT NULL, name VARCHAR(512) DEFAULT NULL, movable TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_7A700CD877153098 (code), UNIQUE INDEX UNIQ_7A700CD85E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cheque (id INT AUTO_INCREMENT NOT NULL, cheque_box_id INT NOT NULL, amount DOUBLE PRECISION DEFAULT NULL, date_of_collection DATE DEFAULT NULL, quote VARCHAR(510) DEFAULT NULL, INDEX IDX_A0BBFDE9346C55BF (cheque_box_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cheque_box (id INT AUTO_INCREMENT NOT NULL, chart_of_accounts_id INT NOT NULL, location_id INT NOT NULL, description VARCHAR(1024) DEFAULT NULL, last_count_date DATE DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_824E6B6A5E237E06 (name), INDEX IDX_824E6B6A196B9FF2 (chart_of_accounts_id), INDEX IDX_824E6B6A64D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact (id INT AUTO_INCREMENT NOT NULL, location_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, civility VARCHAR(64) DEFAULT NULL, UNIQUE INDEX UNIQ_4C62E6385126AC48 (mail), UNIQUE INDEX UNIQ_4C62E638444F97DD (phone), INDEX IDX_4C62E63864D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact_customer (contact_id INT NOT NULL, customer_id INT NOT NULL, INDEX IDX_1B1C129EE7A1254A (contact_id), INDEX IDX_1B1C129E9395C3F3 (customer_id), PRIMARY KEY(contact_id, customer_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact_supplier (contact_id INT NOT NULL, supplier_id INT NOT NULL, INDEX IDX_10FF0E9E7A1254A (contact_id), INDEX IDX_10FF0E92ADD6D8C (supplier_id), PRIMARY KEY(contact_id, supplier_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer (id INT AUTO_INCREMENT NOT NULL, chart_of_accounts_id INT DEFAULT NULL, location_id INT DEFAULT NULL, administrative_identifier_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, impression_access TINYINT(1) DEFAULT NULL, INDEX IDX_81398E09196B9FF2 (chart_of_accounts_id), INDEX IDX_81398E0964D218E (location_id), INDEX IDX_81398E093FBAE8D2 (administrative_identifier_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE demande (id INT AUTO_INCREMENT NOT NULL, profil_id INT DEFAULT NULL, date_debut DATETIME DEFAULT NULL, date_fin DATETIME DEFAULT NULL, nombre_personne INT DEFAULT NULL, planning VARCHAR(255) DEFAULT NULL, double_maillage TINYINT(1) NOT NULL, name VARCHAR(255) DEFAULT NULL, INDEX IDX_2694D7A5275ED078 (profil_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE demande_association (demande_id INT NOT NULL, association_id INT NOT NULL, INDEX IDX_5CA27EB880E95E18 (demande_id), INDEX IDX_5CA27EB8EFB9C8A5 (association_id), PRIMARY KEY(demande_id, association_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE demande_equipe_elu (demande_id INT NOT NULL, equipe_elu_id INT NOT NULL, INDEX IDX_516BAE6C80E95E18 (demande_id), INDEX IDX_516BAE6C7DEF8F22 (equipe_elu_id), PRIMARY KEY(demande_id, equipe_elu_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE demande_formation (demande_id INT NOT NULL, formation_id INT NOT NULL, INDEX IDX_356CDB6A80E95E18 (demande_id), INDEX IDX_356CDB6A5200282E (formation_id), PRIMARY KEY(demande_id, formation_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE editor (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, mail VARCHAR(255) DEFAULT NULL, instagram VARCHAR(255) DEFAULT NULL, facebook VARCHAR(255) DEFAULT NULL, adress VARCHAR(255) DEFAULT NULL, description VARCHAR(1024) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_CCF1F1BAA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE equipe_elu (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, categorie VARCHAR(512) DEFAULT NULL, description VARCHAR(2048) DEFAULT NULL, adresse_mail VARCHAR(255) DEFAULT NULL, etablissement VARCHAR(255) DEFAULT NULL, date_election DATE DEFAULT NULL, duree_mandat INT DEFAULT NULL, fede_filliere VARCHAR(512) DEFAULT NULL, UNIQUE INDEX UNIQ_A7A7A4CD77153098 (code), UNIQUE INDEX UNIQ_A7A7A4CD5E237E06 (name), UNIQUE INDEX UNIQ_A7A7A4CDA1207B9E (adresse_mail), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE equipe_elu_profil (equipe_elu_id INT NOT NULL, profil_id INT NOT NULL, INDEX IDX_22199A9D7DEF8F22 (equipe_elu_id), INDEX IDX_22199A9D275ED078 (profil_id), PRIMARY KEY(equipe_elu_id, profil_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE evenement (id INT AUTO_INCREMENT NOT NULL, lieu_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, date_debut DATETIME DEFAULT NULL, date_fin DATETIME DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, parcours LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', autorisation_photo TINYINT(1) DEFAULT NULL, mode_paiement LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', covoiturage TINYINT(1) DEFAULT NULL, parcours_obligatoire TINYINT(1) DEFAULT NULL, visible TINYINT(1) DEFAULT NULL, date_fin_inscription DATETIME DEFAULT NULL, nombre_place INT DEFAULT NULL, UNIQUE INDEX UNIQ_B26681E5E237E06 (name), INDEX IDX_B26681E6AB213CC (lieu_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event (id INT AUTO_INCREMENT NOT NULL, location_id INT DEFAULT NULL, exercice_id INT NOT NULL, financement_line_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, start_date DATETIME NOT NULL, end_date DATETIME NOT NULL, description VARCHAR(1024) DEFAULT NULL, amount DOUBLE PRECISION DEFAULT NULL, UNIQUE INDEX UNIQ_3BAE0AA777153098 (code), INDEX IDX_3BAE0AA764D218E (location_id), INDEX IDX_3BAE0AA789D40298 (exercice_id), INDEX IDX_3BAE0AA7735B1F8A (financement_line_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exercice (id INT AUTO_INCREMENT NOT NULL, annee INT NOT NULL, UNIQUE INDEX UNIQ_E418C74DDE92C5CF (annee), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE expense_report (id INT AUTO_INCREMENT NOT NULL, transaction_id INT DEFAULT NULL, supplier_id INT NOT NULL, exercice_id INT NOT NULL, motif VARCHAR(1024) DEFAULT NULL, code INT DEFAULT NULL, date DATE DEFAULT NULL, comfirm TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_280A69177153098 (code), INDEX IDX_280A6912FC0CB0F (transaction_id), INDEX IDX_280A6912ADD6D8C (supplier_id), INDEX IDX_280A69189D40298 (exercice_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE expense_report_line (id INT AUTO_INCREMENT NOT NULL, expense_report_id INT NOT NULL, date DATE DEFAULT NULL, object VARCHAR(255) DEFAULT NULL, amount DOUBLE PRECISION DEFAULT NULL, document VARCHAR(1024) DEFAULT NULL, INDEX IDX_DB54F5968F758FBA (expense_report_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE expense_report_route_line (id INT AUTO_INCREMENT NOT NULL, repay_grid_id INT DEFAULT NULL, expense_report_id INT NOT NULL, date DATE DEFAULT NULL, start VARCHAR(255) DEFAULT NULL, end VARCHAR(255) DEFAULT NULL, distance DOUBLE PRECISION DEFAULT NULL, travel_mean VARCHAR(255) DEFAULT NULL, amount DOUBLE PRECISION DEFAULT NULL, INDEX IDX_87B5163BC4B18AE7 (repay_grid_id), INDEX IDX_87B5163B8F758FBA (expense_report_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE federation (id INT AUTO_INCREMENT NOT NULL, social_reason VARCHAR(255) DEFAULT NULL, statutory_object VARCHAR(2048) DEFAULT NULL, creation_date DATE DEFAULT NULL, represented_by VARCHAR(255) DEFAULT NULL, rna VARCHAR(15) DEFAULT NULL, vat_number VARCHAR(15) DEFAULT NULL, currency VARCHAR(1) DEFAULT NULL, UNIQUE INDEX UNIQ_AD241BCD25F3EAD0 (social_reason), UNIQUE INDEX UNIQ_AD241BCD69FF72CB (rna), UNIQUE INDEX UNIQ_AD241BCD8910B08D (vat_number), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE financement (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, financeur VARCHAR(255) DEFAULT NULL, amount DOUBLE PRECISION DEFAULT NULL, pluriannuel INT DEFAULT NULL, date_versement DATE DEFAULT NULL, date_signature DATE DEFAULT NULL, flechee TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE financement_line (id INT AUTO_INCREMENT NOT NULL, financement_id INT NOT NULL, libellee VARCHAR(255) DEFAULT NULL, amount DOUBLE PRECISION DEFAULT NULL, description VARCHAR(1024) DEFAULT NULL, reporter DOUBLE PRECISION DEFAULT NULL, INDEX IDX_2D912760A737ED74 (financement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE formation (id INT AUTO_INCREMENT NOT NULL, badge_id INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, categorie LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', description VARCHAR(2048) DEFAULT NULL, pre_requis VARCHAR(1024) DEFAULT NULL, duration TIME DEFAULT NULL, public_cible VARCHAR(1024) DEFAULT NULL, opg VARCHAR(2048) DEFAULT NULL, UNIQUE INDEX UNIQ_404021BF77153098 (code), INDEX IDX_404021BFF7A2C2FC (badge_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fund_box (id INT AUTO_INCREMENT NOT NULL, chart_of_accounts_id INT DEFAULT NULL, location_id INT DEFAULT NULL, description VARCHAR(1024) DEFAULT NULL, last_count_date DATE NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_F73CB8A25E237E06 (name), INDEX IDX_F73CB8A2196B9FF2 (chart_of_accounts_id), INDEX IDX_F73CB8A264D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fund_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, amount DOUBLE PRECISION NOT NULL, UNIQUE INDEX UNIQ_72F5D9AF5E237E06 (name), UNIQUE INDEX UNIQ_72F5D9AF8EA17042 (amount), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fund_type_fund_box (id INT AUTO_INCREMENT NOT NULL, fund_type_id INT NOT NULL, fund_box_id INT NOT NULL, horrodateur DATETIME NOT NULL, quantity INT NOT NULL, INDEX IDX_8B1F647C2948A7DA (fund_type_id), INDEX IDX_8B1F647CBFCE14FE (fund_box_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `group` (id INT AUTO_INCREMENT NOT NULL, include_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_6DC044C5EA0ECADF (include_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE impression (id INT AUTO_INCREMENT NOT NULL, invoice_id INT DEFAULT NULL, customer_id INT DEFAULT NULL, exercice_id INT NOT NULL, event_id INT DEFAULT NULL, datetime DATETIME NOT NULL, name VARCHAR(255) NOT NULL, format VARCHAR(255) NOT NULL, recto_verso TINYINT(1) NOT NULL, couleur TINYINT(1) NOT NULL, quantite INT NOT NULL, facture_fin_du_mois TINYINT(1) NOT NULL, INDEX IDX_245BB1B12989F1FD (invoice_id), INDEX IDX_245BB1B19395C3F3 (customer_id), INDEX IDX_245BB1B189D40298 (exercice_id), INDEX IDX_245BB1B171F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE institution (id INT AUTO_INCREMENT NOT NULL, administrative_identifier_id INT DEFAULT NULL, federation_id INT DEFAULT NULL, location_id INT DEFAULT NULL, headquarter TINYINT(1) NOT NULL, open TINYINT(1) NOT NULL, INDEX IDX_3A9F98E53FBAE8D2 (administrative_identifier_id), INDEX IDX_3A9F98E56A03EFC5 (federation_id), INDEX IDX_3A9F98E564D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice (id INT AUTO_INCREMENT NOT NULL, transaction_id INT DEFAULT NULL, customer_id INT DEFAULT NULL, exercice_id INT NOT NULL, creation_date DATE NOT NULL, acquitted TINYINT(1) NOT NULL, ready TINYINT(1) NOT NULL, comfirm TINYINT(1) NOT NULL, credit TINYINT(1) NOT NULL, code VARCHAR(255) NOT NULL, category VARCHAR(64) DEFAULT NULL, UNIQUE INDEX UNIQ_9065174477153098 (code), INDEX IDX_906517442FC0CB0F (transaction_id), INDEX IDX_906517449395C3F3 (customer_id), INDEX IDX_9065174489D40298 (exercice_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice_line (id INT AUTO_INCREMENT NOT NULL, invoice_id INT DEFAULT NULL, catalog_discount_id INT DEFAULT NULL, catalog_service_id INT DEFAULT NULL, discount DOUBLE PRECISION DEFAULT NULL, quote VARCHAR(255) DEFAULT NULL, quantity DOUBLE PRECISION NOT NULL, INDEX IDX_D3D1D6932989F1FD (invoice_id), INDEX IDX_D3D1D6935DC840B1 (catalog_discount_id), INDEX IDX_D3D1D69358765B3D (catalog_service_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lieux (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, salle VARCHAR(255) DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, code_postale VARCHAR(255) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_9E44A8AE77153098 (code), UNIQUE INDEX UNIQ_9E44A8AE5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE location (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(64) NOT NULL, adress VARCHAR(255) DEFAULT NULL, zip_code INT DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_deadline (id INT AUTO_INCREMENT NOT NULL, invoice_id INT DEFAULT NULL, expected_payment_date DATE NOT NULL, expected_amount DOUBLE PRECISION NOT NULL, expected_means VARCHAR(255) NOT NULL, actual_payment_date DATE DEFAULT NULL, actual_amount DOUBLE PRECISION DEFAULT NULL, actual_means VARCHAR(255) DEFAULT NULL, INDEX IDX_F781369A2989F1FD (invoice_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post (id INT AUTO_INCREMENT NOT NULL, editor_id INT NOT NULL, titre VARCHAR(255) NOT NULL, description VARCHAR(2048) DEFAULT NULL, visible TINYINT(1) NOT NULL, end_date DATETIME NOT NULL, INDEX IDX_5A8A6C8D6995AC4C (editor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_group (post_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_FADBC82A4B89032C (post_id), INDEX IDX_FADBC82AFE54D947 (group_id), PRIMARY KEY(post_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE profil (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, last_name VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, pronom VARCHAR(255) NOT NULL, date_of_birth DATE NOT NULL, UNIQUE INDEX UNIQ_E6D6B29777153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE profil_seance (profil_id INT NOT NULL, seance_id INT NOT NULL, INDEX IDX_AE82745C275ED078 (profil_id), INDEX IDX_AE82745CE3797A94 (seance_id), PRIMARY KEY(profil_id, seance_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE repay_grid (id INT AUTO_INCREMENT NOT NULL, caracteristique VARCHAR(255) NOT NULL, travel_mean VARCHAR(255) NOT NULL, start VARCHAR(255) NOT NULL, end VARCHAR(255) NOT NULL, amount DOUBLE PRECISION NOT NULL, number_people INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7CE748AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE retour (id INT AUTO_INCREMENT NOT NULL, seance_id INT DEFAULT NULL, profil_id INT DEFAULT NULL, note_contenu INT NOT NULL, remarque_contenu VARCHAR(255) DEFAULT NULL, note_animation INT NOT NULL, remarque_animation VARCHAR(255) DEFAULT NULL, note_implication INT NOT NULL, remarque_implication VARCHAR(255) DEFAULT NULL, note_reponse_atente INT NOT NULL, remarque_reponse_attente VARCHAR(255) DEFAULT NULL, note_niv_competence INT NOT NULL, remarque_niv_competence VARCHAR(255) DEFAULT NULL, note_utilite INT NOT NULL, remarque_utilite VARCHAR(255) DEFAULT NULL, note_generale INT NOT NULL, remarque_generale VARCHAR(255) DEFAULT NULL, apport_generale VARCHAR(255) DEFAULT NULL, plus_aimer VARCHAR(255) DEFAULT NULL, moins_aimer VARCHAR(255) DEFAULT NULL, aimer_voir VARCHAR(255) DEFAULT NULL, mot_fin VARCHAR(255) DEFAULT NULL, INDEX IDX_ED6FD321E3797A94 (seance_id), INDEX IDX_ED6FD321275ED078 (profil_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seance (id INT AUTO_INCREMENT NOT NULL, formation_id INT DEFAULT NULL, evenement_id INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, datetime DATETIME NOT NULL, nombreplace INT NOT NULL, visible TINYINT(1) NOT NULL, parcours VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_DF7DFD0E77153098 (code), INDEX IDX_DF7DFD0E5200282E (formation_id), INDEX IDX_DF7DFD0EFD02F13 (evenement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seance_lieux (seance_id INT NOT NULL, lieux_id INT NOT NULL, INDEX IDX_8152BBE2E3797A94 (seance_id), INDEX IDX_8152BBE2A2C806AC (lieux_id), PRIMARY KEY(seance_id, lieux_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seance_profil (lieu_id INT NOT NULL, horrodateur DATETIME DEFAULT NULL, attente VARCHAR(255) DEFAULT NULL, autorisation_photo TINYINT(1) DEFAULT NULL, covoiturage TINYINT(1) DEFAULT NULL, mode_paiement VARCHAR(255) DEFAULT NULL, profil_ID INT NOT NULL, seance_ID INT NOT NULL, INDEX IDX_99A3A93F89B4D412 (profil_ID), INDEX IDX_99A3A93F4D937EFE (seance_ID), INDEX IDX_99A3A93F6AB213CC (lieu_id), PRIMARY KEY(profil_ID, seance_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE supplier (id INT AUTO_INCREMENT NOT NULL, chart_of_accounts_id INT DEFAULT NULL, location_id INT DEFAULT NULL, administrative_identifier_id INT DEFAULT NULL, customer_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_9B2A6C7E5E237E06 (name), INDEX IDX_9B2A6C7E196B9FF2 (chart_of_accounts_id), INDEX IDX_9B2A6C7E64D218E (location_id), INDEX IDX_9B2A6C7E3FBAE8D2 (administrative_identifier_id), UNIQUE INDEX UNIQ_9B2A6C7E9395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transaction (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, bp_id INT DEFAULT NULL, exercice_id INT NOT NULL, financement_line_id INT DEFAULT NULL, code BIGINT NOT NULL, closure TINYINT(1) NOT NULL, quote VARCHAR(1024) DEFAULT NULL, UNIQUE INDEX UNIQ_723705D177153098 (code), INDEX IDX_723705D171F7E88B (event_id), INDEX IDX_723705D1D7EF6F8E (bp_id), INDEX IDX_723705D189D40298 (exercice_id), INDEX IDX_723705D1735B1F8A (financement_line_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transaction_line (id INT AUTO_INCREMENT NOT NULL, transaction_id INT DEFAULT NULL, chart_of_accounts_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, date DATE NOT NULL, amount DOUBLE PRECISION NOT NULL, url_proof VARCHAR(255) DEFAULT NULL, quote VARCHAR(1024) DEFAULT NULL, INDEX IDX_33578A572FC0CB0F (transaction_id), INDEX IDX_33578A57196B9FF2 (chart_of_accounts_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, profil_id INT DEFAULT NULL, customer_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), UNIQUE INDEX UNIQ_8D93D649275ED078 (profil_id), UNIQUE INDEX UNIQ_8D93D6499395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE association_profil ADD CONSTRAINT FK_D5A287E0EFB9C8A5 FOREIGN KEY (association_id) REFERENCES association (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE association_profil ADD CONSTRAINT FK_D5A287E0275ED078 FOREIGN KEY (profil_id) REFERENCES profil (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE badge_profil ADD CONSTRAINT FK_D46A11D2F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE badge_profil ADD CONSTRAINT FK_D46A11D2275ED078 FOREIGN KEY (profil_id) REFERENCES profil (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bank_account ADD CONSTRAINT FK_53A23E0A196B9FF2 FOREIGN KEY (chart_of_accounts_id) REFERENCES chart_of_accounts (id)');
        $this->addSql('ALTER TABLE bank_account ADD CONSTRAINT FK_53A23E0A64D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE bank_detail ADD CONSTRAINT FK_E6350EE9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE bp ADD CONSTRAINT FK_46176AE689D40298 FOREIGN KEY (exercice_id) REFERENCES exercice (id)');
        $this->addSql('ALTER TABLE cheque ADD CONSTRAINT FK_A0BBFDE9346C55BF FOREIGN KEY (cheque_box_id) REFERENCES cheque_box (id)');
        $this->addSql('ALTER TABLE cheque_box ADD CONSTRAINT FK_824E6B6A196B9FF2 FOREIGN KEY (chart_of_accounts_id) REFERENCES chart_of_accounts (id)');
        $this->addSql('ALTER TABLE cheque_box ADD CONSTRAINT FK_824E6B6A64D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E63864D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE contact_customer ADD CONSTRAINT FK_1B1C129EE7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact_customer ADD CONSTRAINT FK_1B1C129E9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact_supplier ADD CONSTRAINT FK_10FF0E9E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact_supplier ADD CONSTRAINT FK_10FF0E92ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09196B9FF2 FOREIGN KEY (chart_of_accounts_id) REFERENCES chart_of_accounts (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E0964D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E093FBAE8D2 FOREIGN KEY (administrative_identifier_id) REFERENCES administrative_identifier (id)');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A5275ED078 FOREIGN KEY (profil_id) REFERENCES profil (id)');
        $this->addSql('ALTER TABLE demande_association ADD CONSTRAINT FK_5CA27EB880E95E18 FOREIGN KEY (demande_id) REFERENCES demande (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demande_association ADD CONSTRAINT FK_5CA27EB8EFB9C8A5 FOREIGN KEY (association_id) REFERENCES association (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demande_equipe_elu ADD CONSTRAINT FK_516BAE6C80E95E18 FOREIGN KEY (demande_id) REFERENCES demande (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demande_equipe_elu ADD CONSTRAINT FK_516BAE6C7DEF8F22 FOREIGN KEY (equipe_elu_id) REFERENCES equipe_elu (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demande_formation ADD CONSTRAINT FK_356CDB6A80E95E18 FOREIGN KEY (demande_id) REFERENCES demande (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demande_formation ADD CONSTRAINT FK_356CDB6A5200282E FOREIGN KEY (formation_id) REFERENCES formation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE editor ADD CONSTRAINT FK_CCF1F1BAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE equipe_elu_profil ADD CONSTRAINT FK_22199A9D7DEF8F22 FOREIGN KEY (equipe_elu_id) REFERENCES equipe_elu (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE equipe_elu_profil ADD CONSTRAINT FK_22199A9D275ED078 FOREIGN KEY (profil_id) REFERENCES profil (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT FK_B26681E6AB213CC FOREIGN KEY (lieu_id) REFERENCES lieux (id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA764D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA789D40298 FOREIGN KEY (exercice_id) REFERENCES exercice (id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7735B1F8A FOREIGN KEY (financement_line_id) REFERENCES financement_line (id)');
        $this->addSql('ALTER TABLE expense_report ADD CONSTRAINT FK_280A6912FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transaction (id)');
        $this->addSql('ALTER TABLE expense_report ADD CONSTRAINT FK_280A6912ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id)');
        $this->addSql('ALTER TABLE expense_report ADD CONSTRAINT FK_280A69189D40298 FOREIGN KEY (exercice_id) REFERENCES exercice (id)');
        $this->addSql('ALTER TABLE expense_report_line ADD CONSTRAINT FK_DB54F5968F758FBA FOREIGN KEY (expense_report_id) REFERENCES expense_report (id)');
        $this->addSql('ALTER TABLE expense_report_route_line ADD CONSTRAINT FK_87B5163BC4B18AE7 FOREIGN KEY (repay_grid_id) REFERENCES repay_grid (id)');
        $this->addSql('ALTER TABLE expense_report_route_line ADD CONSTRAINT FK_87B5163B8F758FBA FOREIGN KEY (expense_report_id) REFERENCES expense_report (id)');
        $this->addSql('ALTER TABLE financement_line ADD CONSTRAINT FK_2D912760A737ED74 FOREIGN KEY (financement_id) REFERENCES financement (id)');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BFF7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id)');
        $this->addSql('ALTER TABLE fund_box ADD CONSTRAINT FK_F73CB8A2196B9FF2 FOREIGN KEY (chart_of_accounts_id) REFERENCES chart_of_accounts (id)');
        $this->addSql('ALTER TABLE fund_box ADD CONSTRAINT FK_F73CB8A264D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE fund_type_fund_box ADD CONSTRAINT FK_8B1F647C2948A7DA FOREIGN KEY (fund_type_id) REFERENCES fund_type (id)');
        $this->addSql('ALTER TABLE fund_type_fund_box ADD CONSTRAINT FK_8B1F647CBFCE14FE FOREIGN KEY (fund_box_id) REFERENCES fund_box (id)');
        $this->addSql('ALTER TABLE `group` ADD CONSTRAINT FK_6DC044C5EA0ECADF FOREIGN KEY (include_id) REFERENCES `group` (id)');
        $this->addSql('ALTER TABLE impression ADD CONSTRAINT FK_245BB1B12989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE impression ADD CONSTRAINT FK_245BB1B19395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE impression ADD CONSTRAINT FK_245BB1B189D40298 FOREIGN KEY (exercice_id) REFERENCES exercice (id)');
        $this->addSql('ALTER TABLE impression ADD CONSTRAINT FK_245BB1B171F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE institution ADD CONSTRAINT FK_3A9F98E53FBAE8D2 FOREIGN KEY (administrative_identifier_id) REFERENCES administrative_identifier (id)');
        $this->addSql('ALTER TABLE institution ADD CONSTRAINT FK_3A9F98E56A03EFC5 FOREIGN KEY (federation_id) REFERENCES federation (id)');
        $this->addSql('ALTER TABLE institution ADD CONSTRAINT FK_3A9F98E564D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517442FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transaction (id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517449395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_9065174489D40298 FOREIGN KEY (exercice_id) REFERENCES exercice (id)');
        $this->addSql('ALTER TABLE invoice_line ADD CONSTRAINT FK_D3D1D6932989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE invoice_line ADD CONSTRAINT FK_D3D1D6935DC840B1 FOREIGN KEY (catalog_discount_id) REFERENCES catalog_discount (id)');
        $this->addSql('ALTER TABLE invoice_line ADD CONSTRAINT FK_D3D1D69358765B3D FOREIGN KEY (catalog_service_id) REFERENCES catalog_service (id)');
        $this->addSql('ALTER TABLE payment_deadline ADD CONSTRAINT FK_F781369A2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D6995AC4C FOREIGN KEY (editor_id) REFERENCES editor (id)');
        $this->addSql('ALTER TABLE post_group ADD CONSTRAINT FK_FADBC82A4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_group ADD CONSTRAINT FK_FADBC82AFE54D947 FOREIGN KEY (group_id) REFERENCES `group` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE profil_seance ADD CONSTRAINT FK_AE82745C275ED078 FOREIGN KEY (profil_id) REFERENCES profil (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE profil_seance ADD CONSTRAINT FK_AE82745CE3797A94 FOREIGN KEY (seance_id) REFERENCES seance (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE retour ADD CONSTRAINT FK_ED6FD321E3797A94 FOREIGN KEY (seance_id) REFERENCES seance (id)');
        $this->addSql('ALTER TABLE retour ADD CONSTRAINT FK_ED6FD321275ED078 FOREIGN KEY (profil_id) REFERENCES profil (id)');
        $this->addSql('ALTER TABLE seance ADD CONSTRAINT FK_DF7DFD0E5200282E FOREIGN KEY (formation_id) REFERENCES formation (id)');
        $this->addSql('ALTER TABLE seance ADD CONSTRAINT FK_DF7DFD0EFD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id)');
        $this->addSql('ALTER TABLE seance_lieux ADD CONSTRAINT FK_8152BBE2E3797A94 FOREIGN KEY (seance_id) REFERENCES seance (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE seance_lieux ADD CONSTRAINT FK_8152BBE2A2C806AC FOREIGN KEY (lieux_id) REFERENCES lieux (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE seance_profil ADD CONSTRAINT FK_99A3A93F89B4D412 FOREIGN KEY (profil_ID) REFERENCES profil (id)');
        $this->addSql('ALTER TABLE seance_profil ADD CONSTRAINT FK_99A3A93F4D937EFE FOREIGN KEY (seance_ID) REFERENCES seance (id)');
        $this->addSql('ALTER TABLE seance_profil ADD CONSTRAINT FK_99A3A93F6AB213CC FOREIGN KEY (lieu_id) REFERENCES lieux (id)');
        $this->addSql('ALTER TABLE supplier ADD CONSTRAINT FK_9B2A6C7E196B9FF2 FOREIGN KEY (chart_of_accounts_id) REFERENCES chart_of_accounts (id)');
        $this->addSql('ALTER TABLE supplier ADD CONSTRAINT FK_9B2A6C7E64D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE supplier ADD CONSTRAINT FK_9B2A6C7E3FBAE8D2 FOREIGN KEY (administrative_identifier_id) REFERENCES administrative_identifier (id)');
        $this->addSql('ALTER TABLE supplier ADD CONSTRAINT FK_9B2A6C7E9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D171F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1D7EF6F8E FOREIGN KEY (bp_id) REFERENCES bp (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D189D40298 FOREIGN KEY (exercice_id) REFERENCES exercice (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1735B1F8A FOREIGN KEY (financement_line_id) REFERENCES financement_line (id)');
        $this->addSql('ALTER TABLE transaction_line ADD CONSTRAINT FK_33578A572FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transaction (id)');
        $this->addSql('ALTER TABLE transaction_line ADD CONSTRAINT FK_33578A57196B9FF2 FOREIGN KEY (chart_of_accounts_id) REFERENCES chart_of_accounts (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649275ED078 FOREIGN KEY (profil_id) REFERENCES profil (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6499395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE association_profil DROP FOREIGN KEY FK_D5A287E0EFB9C8A5');
        $this->addSql('ALTER TABLE association_profil DROP FOREIGN KEY FK_D5A287E0275ED078');
        $this->addSql('ALTER TABLE badge_profil DROP FOREIGN KEY FK_D46A11D2F7A2C2FC');
        $this->addSql('ALTER TABLE badge_profil DROP FOREIGN KEY FK_D46A11D2275ED078');
        $this->addSql('ALTER TABLE bank_account DROP FOREIGN KEY FK_53A23E0A196B9FF2');
        $this->addSql('ALTER TABLE bank_account DROP FOREIGN KEY FK_53A23E0A64D218E');
        $this->addSql('ALTER TABLE bank_detail DROP FOREIGN KEY FK_E6350EE9395C3F3');
        $this->addSql('ALTER TABLE bp DROP FOREIGN KEY FK_46176AE689D40298');
        $this->addSql('ALTER TABLE cheque DROP FOREIGN KEY FK_A0BBFDE9346C55BF');
        $this->addSql('ALTER TABLE cheque_box DROP FOREIGN KEY FK_824E6B6A196B9FF2');
        $this->addSql('ALTER TABLE cheque_box DROP FOREIGN KEY FK_824E6B6A64D218E');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY FK_4C62E63864D218E');
        $this->addSql('ALTER TABLE contact_customer DROP FOREIGN KEY FK_1B1C129EE7A1254A');
        $this->addSql('ALTER TABLE contact_customer DROP FOREIGN KEY FK_1B1C129E9395C3F3');
        $this->addSql('ALTER TABLE contact_supplier DROP FOREIGN KEY FK_10FF0E9E7A1254A');
        $this->addSql('ALTER TABLE contact_supplier DROP FOREIGN KEY FK_10FF0E92ADD6D8C');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E09196B9FF2');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E0964D218E');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E093FBAE8D2');
        $this->addSql('ALTER TABLE demande DROP FOREIGN KEY FK_2694D7A5275ED078');
        $this->addSql('ALTER TABLE demande_association DROP FOREIGN KEY FK_5CA27EB880E95E18');
        $this->addSql('ALTER TABLE demande_association DROP FOREIGN KEY FK_5CA27EB8EFB9C8A5');
        $this->addSql('ALTER TABLE demande_equipe_elu DROP FOREIGN KEY FK_516BAE6C80E95E18');
        $this->addSql('ALTER TABLE demande_equipe_elu DROP FOREIGN KEY FK_516BAE6C7DEF8F22');
        $this->addSql('ALTER TABLE demande_formation DROP FOREIGN KEY FK_356CDB6A80E95E18');
        $this->addSql('ALTER TABLE demande_formation DROP FOREIGN KEY FK_356CDB6A5200282E');
        $this->addSql('ALTER TABLE editor DROP FOREIGN KEY FK_CCF1F1BAA76ED395');
        $this->addSql('ALTER TABLE equipe_elu_profil DROP FOREIGN KEY FK_22199A9D7DEF8F22');
        $this->addSql('ALTER TABLE equipe_elu_profil DROP FOREIGN KEY FK_22199A9D275ED078');
        $this->addSql('ALTER TABLE evenement DROP FOREIGN KEY FK_B26681E6AB213CC');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA764D218E');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA789D40298');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7735B1F8A');
        $this->addSql('ALTER TABLE expense_report DROP FOREIGN KEY FK_280A6912FC0CB0F');
        $this->addSql('ALTER TABLE expense_report DROP FOREIGN KEY FK_280A6912ADD6D8C');
        $this->addSql('ALTER TABLE expense_report DROP FOREIGN KEY FK_280A69189D40298');
        $this->addSql('ALTER TABLE expense_report_line DROP FOREIGN KEY FK_DB54F5968F758FBA');
        $this->addSql('ALTER TABLE expense_report_route_line DROP FOREIGN KEY FK_87B5163BC4B18AE7');
        $this->addSql('ALTER TABLE expense_report_route_line DROP FOREIGN KEY FK_87B5163B8F758FBA');
        $this->addSql('ALTER TABLE financement_line DROP FOREIGN KEY FK_2D912760A737ED74');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY FK_404021BFF7A2C2FC');
        $this->addSql('ALTER TABLE fund_box DROP FOREIGN KEY FK_F73CB8A2196B9FF2');
        $this->addSql('ALTER TABLE fund_box DROP FOREIGN KEY FK_F73CB8A264D218E');
        $this->addSql('ALTER TABLE fund_type_fund_box DROP FOREIGN KEY FK_8B1F647C2948A7DA');
        $this->addSql('ALTER TABLE fund_type_fund_box DROP FOREIGN KEY FK_8B1F647CBFCE14FE');
        $this->addSql('ALTER TABLE `group` DROP FOREIGN KEY FK_6DC044C5EA0ECADF');
        $this->addSql('ALTER TABLE impression DROP FOREIGN KEY FK_245BB1B12989F1FD');
        $this->addSql('ALTER TABLE impression DROP FOREIGN KEY FK_245BB1B19395C3F3');
        $this->addSql('ALTER TABLE impression DROP FOREIGN KEY FK_245BB1B189D40298');
        $this->addSql('ALTER TABLE impression DROP FOREIGN KEY FK_245BB1B171F7E88B');
        $this->addSql('ALTER TABLE institution DROP FOREIGN KEY FK_3A9F98E53FBAE8D2');
        $this->addSql('ALTER TABLE institution DROP FOREIGN KEY FK_3A9F98E56A03EFC5');
        $this->addSql('ALTER TABLE institution DROP FOREIGN KEY FK_3A9F98E564D218E');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_906517442FC0CB0F');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_906517449395C3F3');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_9065174489D40298');
        $this->addSql('ALTER TABLE invoice_line DROP FOREIGN KEY FK_D3D1D6932989F1FD');
        $this->addSql('ALTER TABLE invoice_line DROP FOREIGN KEY FK_D3D1D6935DC840B1');
        $this->addSql('ALTER TABLE invoice_line DROP FOREIGN KEY FK_D3D1D69358765B3D');
        $this->addSql('ALTER TABLE payment_deadline DROP FOREIGN KEY FK_F781369A2989F1FD');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8D6995AC4C');
        $this->addSql('ALTER TABLE post_group DROP FOREIGN KEY FK_FADBC82A4B89032C');
        $this->addSql('ALTER TABLE post_group DROP FOREIGN KEY FK_FADBC82AFE54D947');
        $this->addSql('ALTER TABLE profil_seance DROP FOREIGN KEY FK_AE82745C275ED078');
        $this->addSql('ALTER TABLE profil_seance DROP FOREIGN KEY FK_AE82745CE3797A94');
        $this->addSql('ALTER TABLE reset_password_request DROP FOREIGN KEY FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE retour DROP FOREIGN KEY FK_ED6FD321E3797A94');
        $this->addSql('ALTER TABLE retour DROP FOREIGN KEY FK_ED6FD321275ED078');
        $this->addSql('ALTER TABLE seance DROP FOREIGN KEY FK_DF7DFD0E5200282E');
        $this->addSql('ALTER TABLE seance DROP FOREIGN KEY FK_DF7DFD0EFD02F13');
        $this->addSql('ALTER TABLE seance_lieux DROP FOREIGN KEY FK_8152BBE2E3797A94');
        $this->addSql('ALTER TABLE seance_lieux DROP FOREIGN KEY FK_8152BBE2A2C806AC');
        $this->addSql('ALTER TABLE seance_profil DROP FOREIGN KEY FK_99A3A93F89B4D412');
        $this->addSql('ALTER TABLE seance_profil DROP FOREIGN KEY FK_99A3A93F4D937EFE');
        $this->addSql('ALTER TABLE seance_profil DROP FOREIGN KEY FK_99A3A93F6AB213CC');
        $this->addSql('ALTER TABLE supplier DROP FOREIGN KEY FK_9B2A6C7E196B9FF2');
        $this->addSql('ALTER TABLE supplier DROP FOREIGN KEY FK_9B2A6C7E64D218E');
        $this->addSql('ALTER TABLE supplier DROP FOREIGN KEY FK_9B2A6C7E3FBAE8D2');
        $this->addSql('ALTER TABLE supplier DROP FOREIGN KEY FK_9B2A6C7E9395C3F3');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D171F7E88B');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1D7EF6F8E');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D189D40298');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1735B1F8A');
        $this->addSql('ALTER TABLE transaction_line DROP FOREIGN KEY FK_33578A572FC0CB0F');
        $this->addSql('ALTER TABLE transaction_line DROP FOREIGN KEY FK_33578A57196B9FF2');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649275ED078');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6499395C3F3');
        $this->addSql('DROP TABLE administrative_identifier');
        $this->addSql('DROP TABLE association');
        $this->addSql('DROP TABLE association_profil');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE badge_profil');
        $this->addSql('DROP TABLE bank_account');
        $this->addSql('DROP TABLE bank_detail');
        $this->addSql('DROP TABLE bp');
        $this->addSql('DROP TABLE catalog_discount');
        $this->addSql('DROP TABLE catalog_service');
        $this->addSql('DROP TABLE chart_of_accounts');
        $this->addSql('DROP TABLE cheque');
        $this->addSql('DROP TABLE cheque_box');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE contact_customer');
        $this->addSql('DROP TABLE contact_supplier');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE demande');
        $this->addSql('DROP TABLE demande_association');
        $this->addSql('DROP TABLE demande_equipe_elu');
        $this->addSql('DROP TABLE demande_formation');
        $this->addSql('DROP TABLE editor');
        $this->addSql('DROP TABLE equipe_elu');
        $this->addSql('DROP TABLE equipe_elu_profil');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE exercice');
        $this->addSql('DROP TABLE expense_report');
        $this->addSql('DROP TABLE expense_report_line');
        $this->addSql('DROP TABLE expense_report_route_line');
        $this->addSql('DROP TABLE federation');
        $this->addSql('DROP TABLE financement');
        $this->addSql('DROP TABLE financement_line');
        $this->addSql('DROP TABLE formation');
        $this->addSql('DROP TABLE fund_box');
        $this->addSql('DROP TABLE fund_type');
        $this->addSql('DROP TABLE fund_type_fund_box');
        $this->addSql('DROP TABLE `group`');
        $this->addSql('DROP TABLE impression');
        $this->addSql('DROP TABLE institution');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE invoice_line');
        $this->addSql('DROP TABLE lieux');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE payment_deadline');
        $this->addSql('DROP TABLE post');
        $this->addSql('DROP TABLE post_group');
        $this->addSql('DROP TABLE profil');
        $this->addSql('DROP TABLE profil_seance');
        $this->addSql('DROP TABLE repay_grid');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE retour');
        $this->addSql('DROP TABLE seance');
        $this->addSql('DROP TABLE seance_lieux');
        $this->addSql('DROP TABLE seance_profil');
        $this->addSql('DROP TABLE supplier');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE transaction_line');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
